// <auto-generated />
namespace MackTechGroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class guid_course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guid_course));
        
        string IMigrationMetadata.Id
        {
            get { return "202006240237208_guid_course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
