// <auto-generated />
namespace MackTechGroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TotalCreditHours_to_Accounting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TotalCreditHours_to_Accounting));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091704398_TotalCreditHours_to_Accounting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
