// <auto-generated />
namespace MackTechGroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_NotMapped_Fields_to_AssignmentsModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_NotMapped_Fields_to_AssignmentsModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202007010810257_Added_NotMapped_Fields_to_AssignmentsModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
